modLoader="javafml" #mandatory
loaderVersion="[30,)" #mandatory
issueTrackerURL="https://github.com/Andromander/CascadingMemeLag/issues" #optional

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
modId="cml" #mandatory
version="1.4.1" #mandatory
displayName="Cascading Meme Lag" #mandatory
displayURL="https://minecraft.curseforge.com/projects/cascading-meme-lag" #optional
#logoFile="" #optional
credits="The memes for allowing this to be a thing." #optional
authors="Androsa" #optional
description='''
Using super-extensive, highly detailed algorithms and equations, this mod picks out memes loaded into the world in excess, just like cascading worldgen lag. These days people load so many mods, even ones with high meme density, that the memes collate until it starts to overload the world. This mod won't fix it, there's no way to fix it, but it will pick out the memes loading in excess.
'''

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.cml]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[30,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.cml]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.1,]"
    ordering="NONE"
    side="BOTH"
